test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  access_key_id: <%= ENV.fetch("R2_ACCESS_KEY_ID", nil) %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY", nil) %>
  region: auto
  bucket: <%= ENV.fetch("R2_BUCKET", nil) %>
  endpoint: <%= ENV.fetch("R2_ENDPOINT", nil) %>
  force_path_style: true